Repository googleapis/java-pubsublite-spark, pull requests merged in 2021-07, with the labels that each got.

#212 fix: Update dependencies.sh to not break on mac
  .kokoro/coerce_logs.sh
  .kokoro/dependencies.sh
  java.header
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#213 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#220 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#215 deps: update dependency com.google.cloud:google-cloud-pubsublite-parent to v0.16.1
  pom.xml
  src/main/java/com/google/cloud/pubsublite/spark/PslReadDataSourceOptions.java
  src/main/java/com/google/cloud/pubsublite/spark/PslSparkUtils.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/CachedPublishers.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/MultiPartitionCommitterImpl.java
Labels: api: pubsublite, cla: yes

#221 deps: update dependency com.google.cloud:google-cloud-pubsublite to v0.18.0
  pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsublite/spark/AdminUtils.java
  src/main/java/com/google/cloud/pubsublite/spark/PslReadDataSourceOptions.java
  src/main/java/com/google/cloud/pubsublite/spark/PslWriteDataSourceOptions.java
Labels: api: pubsublite, cla: yes
