Repository googleapis/java-pubsublite-spark, pull requests merged in 2021-02, with the labels that each got.

#40 chore: enable nexus staging
  pom.xml
Labels: api: pubsublite, api: pubsublite, cla: yes

#44 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  renovate.json
  synth.metadata
Labels: api: pubsublite, api: pubsublite, cla: yes, context: partial

#49 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  LICENSE
  synth.metadata
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes, context: full

#50 fix: update repo name
  .kokoro/release/publish_javadoc11.cfg
  synth.metadata
Labels: api: pubsublite, api: pubsublite, cla: yes, context: full

#55 deps: update dependency com.google.cloud:google-cloud-pubsublite to v0.10.0
  pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSourceOptions.java
  versions.txt
Labels: api: pubsublite, api: pubsublite, cla: yes

#54 build: set up samples testing
  .kokoro/build.sh
  versions.txt
Labels: api: pubsublite, api: pubsublite, cla: yes, samples

#57 fix: update version
  versions.txt
Labels: api: pubsublite, api: pubsublite, cla: yes

#56 feat: Close clients gracefully
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSource.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchInputPartitionReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#59 fix: update synth.py
  synth.py
Labels: api: pubsublite, api: pubsublite, cla: yes

#60 test: update env vars to export
  .kokoro/build.sh
Labels: api: pubsublite, api: pubsublite, cla: yes

#61 test: add samples secrets
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  synth.py
Labels: api: pubsublite, api: pubsublite, cla: yes, samples

#53 samples: Spark connector word count sample
  samples/README.md
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsublite/spark/AdminUtils.java
  samples/snippets/src/main/java/pubsublite/spark/PublishWords.java
  samples/snippets/src/main/java/pubsublite/spark/WordCount.java
  samples/snippets/src/main/resources/text_snippets.txt
  samples/snippets/src/test/java/pubsublite/spark/SampleIntegrationTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes, samples

#62 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#63 doc: Include mexmessageperbatch in the readme
  .readme-partials.yaml
Labels: api: pubsublite, api: pubsublite, cla: yes

#67 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#68 doc: Update README.md
  .readme-partials.yaml
Labels: api: pubsublite, api: pubsublite, cla: yes

#69 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#72 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes, context: full

#70 test: Fixes integration test nightly build.
  samples/snippets/src/test/java/pubsublite/spark/SampleIntegrationTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#71 release: Update uber jar shadedClassifierName
  pom.xml
  samples/snippets/src/test/java/pubsublite/spark/SampleIntegrationTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#73 docs: Update readme about jar name.
  .readme-partials.yaml
  samples/README.md
  samples/pom.xml
Labels: api: pubsublite, api: pubsublite, cla: yes

#74 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#75 test: Fix flakiness of integration test by ordering column.
  samples/snippets/src/main/java/pubsublite/spark/WordCount.java
  samples/snippets/src/test/java/pubsublite/spark/SampleIntegrationTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#76 docs: Update readme.
  samples/README.md
Labels: api: pubsublite, api: pubsublite, cla: yes

#77 sample: Update sample and readme.
  samples/README.md
  samples/snippets/src/main/java/pubsublite/spark/AdminUtils.java
  samples/snippets/src/main/java/pubsublite/spark/PublishWords.java
Labels: api: pubsublite, api: pubsublite, cla: yes, samples

#81 deps: update dependency com.google.cloud:google-cloud-pubsublite to v0.10.0
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsublite/spark/AdminUtils.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#82 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes, context: full

#83 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: full

#84 build: reduce download junk in log files
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes, context: full

#87 fix: Better error message when subscription path is invalid.
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSourceOptions.java
  src/test/java/com/google/cloud/pubsublite/spark/PslDataSourceOptionsTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#88 doc: Add sample common issues.
  .readme-partials.yaml
  samples/README.md
Labels: api: pubsublite, api: pubsublite, cla: yes, samples

#89 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#93 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#98 docs: update client lib documentation link
  .repo-metadata.json
Labels: api: pubsublite, api: pubsublite, cla: yes

#99 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#100 docs: Add maven central link.
  .readme-partials.yaml
Labels: api: pubsublite, api: pubsublite, cla: yes

#101 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes
