Repository googleapis/java-pubsublite-spark, pull requests merged in 2021-03, with the labels that each got.

#105 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsublite, api: pubsublite, cla: yes, context: full

#108 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes, context: full

#109 docs: Update gcs public available link
  .readme-partials.yaml
Labels: api: pubsublite, api: pubsublite, cla: yes

#112 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#113 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsublite, api: pubsublite, cla: yes, context: full

#115 feat: Supports topic partition increase.
  clirr-ignored-differences.xml
  src/main/java/com/google/cloud/pubsublite/spark/CachedPartitionCountReader.java
  src/main/java/com/google/cloud/pubsublite/spark/LimitingHeadOffsetReader.java
  src/main/java/com/google/cloud/pubsublite/spark/MultiPartitionCommitterImpl.java
  src/main/java/com/google/cloud/pubsublite/spark/PartitionCountReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSource.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
  src/test/java/com/google/cloud/pubsublite/spark/LimitingHeadOffsetReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/MultiPartitionCommitterImplTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslContinuousReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslMicroBatchReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/TestingUtils.java
Labels: api: pubsublite, cla: yes
