Repository googleapis/java-pubsublite-spark, pull requests merged in 2021-04, with the labels that each got.

#121 feat: PSL Connector Writer support
  clirr-ignored-differences.xml
  pom.xml
  src/main/java/com/google/cloud/pubsublite/spark/Constants.java
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSource.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataWriter.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataWriterFactory.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslReadDataSourceOptions.java
  src/main/java/com/google/cloud/pubsublite/spark/PslSparkUtils.java
  src/main/java/com/google/cloud/pubsublite/spark/PslStreamWriter.java
  src/main/java/com/google/cloud/pubsublite/spark/PslWriteDataSourceOptions.java
  src/main/java/com/google/cloud/pubsublite/spark/PslWriterCommitMessage.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/CachedPartitionCountReader.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/CachedPublishers.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/LimitingHeadOffsetReader.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/MultiPartitionCommitter.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/MultiPartitionCommitterImpl.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/PartitionCountReader.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/PartitionSubscriberFactory.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/PerTopicHeadOffsetReader.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/PslCredentialsProvider.java
  src/main/java/com/google/cloud/pubsublite/spark/internal/PublisherFactory.java
  src/test/java/com/google/cloud/pubsublite/spark/PslContinuousReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslDataWriterTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslMicroBatchReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslReadDataSourceOptionsTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslSparkUtilsTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslStreamWriterTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslWriteDataSourceOptionsTest.java
  src/test/java/com/google/cloud/pubsublite/spark/internal/LimitingHeadOffsetReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/internal/MultiPartitionCommitterImplTest.java
Labels: api: pubsublite, cla: yes

#127 fix: Move Spark constants into its own class.
  clirr-ignored-differences.xml
  src/main/java/com/google/cloud/pubsublite/spark/Constants.java
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslSparkUtils.java
  src/main/java/com/google/cloud/pubsublite/spark/SparkStructs.java
  src/test/java/com/google/cloud/pubsublite/spark/PslDataWriterTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslSparkUtilsTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslStreamWriterTest.java
Labels: api: pubsublite, cla: yes

#133 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#135 chore: add samples test as a required check during presubmit
  .github/sync-repo-settings.yaml
Labels: api: pubsublite, cla: yes, samples

#137 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#132 docs: Add write support documentations
  .readme-partials.yaml
Labels: api: pubsublite, cla: yes

#139 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#138 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#140 docs: fixes typo
  .readme-partials.yaml
Labels: api: pubsublite, cla: yes

#141 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#136 deps: update dependency com.google.cloud:google-cloud-pubsublite to v0.13.1
  pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsublite/spark/AdminUtils.java
Labels: api: pubsublite, cla: yes

#143 deps: renovate bot ignore scala-library and caffeine deps.
  renovate.json
Labels: api: pubsublite, cla: yes

#144 chore(deps): update dependency com.google.cloud.samples:shared-configuration to v1.0.22
  .kokoro/build.sh
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/test/java/pubsublite/spark/SampleTestBase.java
  samples/snippets/src/test/java/pubsublite/spark/SamplesIntegrationTest.java
  versions.txt
Labels: api: pubsublite, cla: yes, samples

#149 chore: Re-generated to pick up changes from self
  renovate.json
  synth.metadata
Labels: api: pubsublite, cla: yes, context: none

#151 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#152 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#154 docs: Update doc links for 0.2.0
  README.md
Labels: api: pubsublite, cla: yes

#155 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes, kokoro:force-run
