Repository googleapis/java-pubsublite-spark, pull requests merged in 2021-01, with the labels that each got.

#1 chore: add synth.py and repo-metadata
  .repo-metadata.json
  synth.py
Labels: api: pubsublite, api: pubsublite, cla: yes

#3 feat: PubSub Lite Spark Connector
  .gitignore
  .readme-partials.yaml
  README.md
  pom.xml
  src/main/java/com/google/cloud/pubsublite/spark/Constants.java
  src/main/java/com/google/cloud/pubsublite/spark/LimitingHeadOffsetReader.java
  src/main/java/com/google/cloud/pubsublite/spark/MultiPartitionCommitter.java
  src/main/java/com/google/cloud/pubsublite/spark/MultiPartitionCommitterImpl.java
  src/main/java/com/google/cloud/pubsublite/spark/PartitionSubscriberFactory.java
  src/main/java/com/google/cloud/pubsublite/spark/PerTopicHeadOffsetReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousInputPartition.java
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousInputPartitionReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslCredentialsProvider.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSource.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSourceOptions.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchInputPartition.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchInputPartitionReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslPartitionOffset.java
  src/main/java/com/google/cloud/pubsublite/spark/PslSourceOffset.java
  src/main/java/com/google/cloud/pubsublite/spark/PslSparkUtils.java
  src/main/java/com/google/cloud/pubsublite/spark/SparkPartitionOffset.java
  src/main/java/com/google/cloud/pubsublite/spark/SparkSourceOffset.java
  src/test/java/com/google/cloud/pubsublite/spark/LimitingHeadOffsetReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/MultiPartitionCommitterImplTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslContinuousInputPartitionReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslContinuousReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslMicroBatchInputPartitionReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslMicroBatchReaderTest.java
  src/test/java/com/google/cloud/pubsublite/spark/PslSparkUtilsTest.java
  src/test/java/com/google/cloud/pubsublite/spark/SparkSourceOffsetTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#5 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#6 docs: update readme partials
  .readme-partials.yaml
Labels: api: pubsublite, api: pubsublite, cla: yes

#9 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#7 feat: Fix offsets type check
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousInputPartition.java
  src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#13 feat: update artifactId for fat jar
  pom.xml
Labels: api: pubsublite, api: pubsublite, cla: yes

#15 chore: delete java7.cfg
  .kokoro/nightly/java7.cfg
Labels: api: pubsublite, api: pubsublite, cla: yes

#20 chore: delete presubmit/java7.cfg
  .kokoro/presubmit/java7.cfg
Labels: api: pubsublite, api: pubsublite, cla: yes

#21 chore: create versons.txt
  versions.txt
Labels: api: pubsublite, api: pubsublite, cla: yes

#25 feat: use gson instead of jackson
  pom.xml
  src/main/java/com/google/cloud/pubsublite/spark/SparkSourceOffset.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#24 chore: scaffold samples dir
  .kokoro/nightly/java7.cfg
  .kokoro/presubmit/java7.cfg
  .kokoro/release/publish_javadoc.cfg
  pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.metadata
  synth.py
  versions.txt
Labels: api: pubsublite, api: pubsublite, cla: yes, context: none

#16 docs: update README about section
  .readme-partials.yaml
  .repo-metadata.json
Labels: api: pubsublite, api: pubsublite, cla: yes

#26 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, api: pubsublite, cla: yes

#28 chore: use pubsublite-spark-sql-streaming for package name
  .kokoro/release/publish_javadoc.sh
  renovate.json
  synth.metadata
Labels: api: pubsublite, api: pubsublite, cla: yes, context: partial

#33 chore: create sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: api: pubsublite, api: pubsublite, cla: yes

#35 remove jackson reference
  renovate.json
Labels: api: pubsublite, api: pubsublite, cla: yes

#14 feat: Add max message per batch option
  src/main/java/com/google/cloud/pubsublite/spark/Constants.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSource.java
  src/main/java/com/google/cloud/pubsublite/spark/PslDataSourceOptions.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchInputPartitionReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
  src/main/java/com/google/cloud/pubsublite/spark/PslSparkUtils.java
  src/test/java/com/google/cloud/pubsublite/spark/PslMicroBatchReaderTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes

#37 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: pubsublite, api: pubsublite, automerge, cla: yes

#38 feat: Fixes timestamps and more thorough testing
  src/main/java/com/google/cloud/pubsublite/spark/PslSparkUtils.java
  src/test/java/com/google/cloud/pubsublite/spark/PslSparkUtilsTest.java
Labels: api: pubsublite, api: pubsublite, cla: yes
